### ISSUE TITLE
FEAT CoreData 모델 구축

### ISSUE THREAD

**Issue by LEJMO** [DeveloperAcademy-POSTECH/MC3-Team4-Tworld#4]
## 📝 todo

- [x] CoreData Setting in AppDelegate
- [x] Data Model Setting
- [x] CRUD 기능 구현

**Comment by LEJMO** [comment]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/34985422/179385381-0f54c850-158c-47ac-8319-dab46f9c5d0b.png">
**데이터 구조 Draft 입니다.**
