### ISSUE TITLE
FEAT 수업 추가하기 뷰 UI 구현

### ISSUE THREAD

**Issue by eraser3031** [DeveloperAcademy-POSTECH/MC3-Team4-Tworld#7]
# TODO

- [x] NameView UI
- [x] NameView 수업 시간 입력 기능
- [x] NameView 다음 버튼 비활성화 및 그레디언트 적용
- [x] MembersViewUI
- [x] member delete 기능
- [x] TuitionViewUI
- [x] Font 적용
- [x] padding 테마 적용
- [x] CoreData 연결
- [x] 수업 등록 확인 뷰
- [x] 확인 후 홈으로 돌아가기
